CREATE TABLE Students (
StudentID INT PRIMARY KEY IDENTITY (1,1) NOT NULL,
NAME NVARCHAR(15) NOT NULL)

CREATE TABLE Exams(
ExamID INT PRIMARY KEY NOT NULL	 IDENTITY(101,1),
Name NVARCHAR(15) NOT NULL)

CREATE TABLE StudentsExams
(StudentID INT NOT NULL,
ExamID INT NOT NULL,
PRIMARY KEY(StudentID,ExamID)
)

ALTER TABLE StudentsExams
ADD FOREIGN KEY (StudentID) REFERENCES Students (StudentID)

ALTER TABLE StudentsExams
ADD FOREIGN KEY (ExamID) REFERENCES Exams (ExamID)

INSERT INTO Students
VALUES ('Mila'),('Toni'),('Ron')
SELECT * FROM Students

INSERT INTO Exams 
VALUES ('SpringMVC'),('Neo4J'),('Oracle11g')

INSERT INTO StudentsExams
VALUES (1,101),(1,102),(2,101),(3,103),(2,102),(2,103)